version: '3'

volumes:
  mysql_data:
    driver: local
# based off of https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-mysql.yml
services:
  mysql:
    image: mysql:8.0.32
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: mydb
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command: ["-Djboss.http.port=8084", "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"]
    ports:
      - 8084:8084
    depends_on:
      mysql:
        condition: service_healthy