version: '3'

volumes:
  mysql_data:
    driver: local
# based off of https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-mysql.yml
services:
  encounter-backend:
    container_name: encounter-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.32
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${db_database}
      MYSQL_USER: ${db_username}
      MYSQL_PASSWORD: ${db_password}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${db_database}
      DB_USER: ${db_username}
      DB_PASSWORD: ${db_password}
      KEYCLOAK_USER: ${keycloak_admin_username}
      KEYCLOAK_PASSWORD: ${keycloak_admin_password}
    command: ["-Djboss.http.port=8084", "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"]
    ports:
      - 8084:8084
    depends_on:
      mysql:
        condition: service_healthy